[package]
name = "fraud_detection_3"
version = "0.1.0"
edition = "2024"


[dependencies]
rand = "0.9.2"
rusqlite = { version = "0.37.0", features = ["bundled"] }
tokio = { version = "1.47.1", features = ["full"] }
tracing = "0.1.41"
tracing-appender = "0.2.3"
tracing-subscriber = "0.3.19"
